apiVersion: certmanager.k8s.io/v1alpha2
kind: Certificate
metadata:
  name: multi-k8s-tk-tls
spec:
  secretName: k8s-multi-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: multi-k8s.tk
  dnsNames:
    - multi-k8s.tk
    - www.multi-k8s.tk
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - multi-k8s.tk
          - www.multi-k8s.tk
